# 04_05: special arrays

In [2]:
import math
import collections

import numpy as np
import pandas as pd
import matplotlib.pyplot as pp

%matplotlib inline

In [3]:
discography = np.load('discography.npy')

In [4]:
discography

array([('David Bowie', '1969-11-14', 17),
       ('The Man Who Sold the World', '1970-11-04',  3),
       ('Hunky Dory', '1971-12-17',  5),
       ('Ziggy Stardust', '1972-06-16',  1),
       ('Aladdin Sane', '1973-04-13',  1), ('Pin Ups', '1973-10-19',  1),
       ('Diamond Dogs', '1974-05-24',  1),
       ('Young Americans', '1975-03-07',  2),
       ('Station To Station', '1976-01-23',  5),
       ('Low', '1977-01-14',  2), ('Heroes', '1977-10-14',  3),
       ('Lodger', '1979-05-18',  4)],
      dtype=[('title', '<U32'), ('release', '<M8[D]'), ('toprank', '<i8')])

In [10]:
discography[0]

('David Bowie', '1969-11-14', 17)

In [11]:
discography[0][0]

'David Bowie'

In [12]:
discography[0][1]

numpy.datetime64('1969-11-14')

In [13]:
discography[0]['title']

'David Bowie'

In [14]:
discography['title']

array(['David Bowie', 'The Man Who Sold the World', 'Hunky Dory',
       'Ziggy Stardust', 'Aladdin Sane', 'Pin Ups', 'Diamond Dogs',
       'Young Americans', 'Station To Station', 'Low', 'Heroes', 'Lodger'],
      dtype='<U32')

In [17]:
minidisco = np.zeros(len(discography), dtype=[('title','U16'), ('release','M8[s]')])

In [18]:
minidisco['title'] = discography['title']
minidisco['release'] = discography['release']

In [19]:
minidisco

array([('David Bowie', '1969-11-14T00:00:00'),
       ('The Man Who Sold', '1970-11-04T00:00:00'),
       ('Hunky Dory', '1971-12-17T00:00:00'),
       ('Ziggy Stardust', '1972-06-16T00:00:00'),
       ('Aladdin Sane', '1973-04-13T00:00:00'),
       ('Pin Ups', '1973-10-19T00:00:00'),
       ('Diamond Dogs', '1974-05-24T00:00:00'),
       ('Young Americans', '1975-03-07T00:00:00'),
       ('Station To Stati', '1976-01-23T00:00:00'),
       ('Low', '1977-01-14T00:00:00'), ('Heroes', '1977-10-14T00:00:00'),
       ('Lodger', '1979-05-18T00:00:00')],
      dtype=[('title', '<U16'), ('release', '<M8[s]')])

In [ ]:
np.datetime64('1969')

In [ ]:
np.datetime64('1969-11-14')

In [ ]:
np.datetime64('2015-02-03 12:00')

In [20]:
np.datetime64('2015-02-03 12:00') < np.datetime64('2015-02-03 18:00')

True

In [21]:
np.datetime64('2015-02-03 18:00') - np.datetime64('2015-02-03 12:00')

numpy.timedelta64(360,'m')

In [22]:
np.diff(discography['release'])

array([355, 408, 182, 301, 189, 217, 287, 322, 357, 273, 581],
      dtype='timedelta64[D]')

In [23]:
np.arange(np.datetime64('2015-02-03'), np.datetime64('2015-03-01'))

array(['2015-02-03', '2015-02-04', '2015-02-05', '2015-02-06',
       '2015-02-07', '2015-02-08', '2015-02-09', '2015-02-10',
       '2015-02-11', '2015-02-12', '2015-02-13', '2015-02-14',
       '2015-02-15', '2015-02-16', '2015-02-17', '2015-02-18',
       '2015-02-19', '2015-02-20', '2015-02-21', '2015-02-22',
       '2015-02-23', '2015-02-24', '2015-02-25', '2015-02-26',
       '2015-02-27', '2015-02-28'], dtype='datetime64[D]')

In [26]:
a = np.array([0,1,3,5,7,11])
a > 3

array([False, False, False,  True,  True,  True])

In [27]:
np.ones((3,3)) * np.linspace(0,1,3)

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [28]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [34]:
minidisco = np.array('Station To Station 123', dtype='U16')

In [35]:
minidisco

array('Station To Stati', dtype='<U16')

In [36]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
np.arange(0,1,5)

array([0])